### ISSUE TITLE
cut_wav expects integers

### ISSUE THREAD

**Issue by kookster** [PRX/audio_monster#8]
and there is no reason to - sox can handle when it is not an integer, and other tasks support using sox support the time based format:

```
[[hours:]minutes:]seconds[.frac][t]
A specification of ‘1:30.5’ corresponds to one minute, thirty and ½ seconds. The t suffix is entirely optional (however, see the silence effect for an exception). Note that the component values do not have to be normalized; e.g., ‘1:23:45’, ‘83:45’, ‘79:0285’, ‘1:0:1425’, ‘1::1425’ and ‘5025’ all are legal and equivalent to each other.
```

http://sox.sourceforge.net/sox.html

**Comment by pkarman** [comment]
this line in particular throws an error if the length param is a string:

https://github.com/PRX/audio_monster/blob/master/lib/audio_monster/monster.rb#L622

**Comment by kookster** [comment]
absolutely. That is the check that `slice` doesn't do, for example, which I wrote more recently.

**Comment by kookster** [comment]
looks like that PR fixed it, closing
